inicio centrado y responsive
monoguerin/warriortoysHP pull request #3
Opened 2023-08-03 17:11 UTC by matbui

correción de div inicio, utilizando clases de boostrap para mantener el container centrado y responsive en mobil

2023-08-03 20:25 UTC, monoguerin commented
Falta borrar el archivo extra que subio y mirar cmo hacer para que no se suba.. como ignorarlo

2023-08-03 20:27 UTC, monoguerin commented on home.html
>          .justify-content-space-evenly {
por q no usar la clase de bootstrap `.justify-content-evenly` ?

2023-08-03 20:29 UTC, monoguerin commented on home.html
> +                <p style="background: red; text-align: center; width: 20%;">INICIO</p>
el width no debe ser hardcodeado a 20%, el width tiene q venir del contenido, trate de quitar los vw-100 vh-100 q tiene en los containers

2023-08-03 20:31 UTC, monoguerin requested changes
los estilos aun estan muy "macheteados" piense como si estuviera haciendolos normal con CSS no necesita 10 estilos para que quede asi, tal vez con 2 o max 3 se logra lo q necesita

2023-08-07 19:13 UTC, matbui commented on home.html
> +                <p style="background: red; text-align: center; width: 20%;">INICIO</p>
actualizado

2023-08-07 19:14 UTC, matbui commented on home.html
>          .justify-content-space-evenly {
listo, ya lo usé, habia leido que no existia ese estilo en bootstrap y por eso no lo habia usado

2023-08-08 15:12 UTC, monoguerin submitted a review, later dismissed

2023-08-08 20:56 UTC, monoguerin approved these changes

2023-08-08 20:56 UTC, merged